### ISSUE TITLE
Page Not found - Docs

### ISSUE THREAD

**Issue by itsraghz** [sqlcomponents/sqlcomponents#163]
**Describe the bug**
The Docs link is throwing 404. https://sqlcomponents.org/docs/guides/instalation/ 

**To Reproduce**

1. Go to 'https://sqlcomponents.org/'
2. Click on 'https://sqlcomponents.org/docs/guides/instalation/'
3. See error - Page Not found 

**Expected behavior**
The page should load. 

**Screenshots**
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/ad38d135-1edb-4d63-b185-e26b8403710b">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS 14.6.1 (23G93)
- Browser [e.g. chrome, safari] Firefox 
- Version [e.g. 22] 129.0.2

**Comment by rmhari** [comment]
Fixed

**Comment by itsraghz** [comment]
Yes, this looks good now
