### ISSUE TITLE
Spelling Mistake - on Installation

### ISSUE THREAD

**Issue by itsraghz** [sqlcomponents/sqlcomponents#164]
**Describe the bug**
The Installation word is wrongly spelt in the URL https://sqlcomponents.org/docs/guides/instalation/

**To Reproduce**

1. Go to 'https://sqlcomponents.org/docs/guides'
2. Click on 'https://sqlcomponents.org/docs/guides/instalation/'
3. The word instalation is wrong. It should be installation.

**Expected behavior**
It should be 'installation'

**Screenshots**
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/95e47592-7519-4554-9279-0d6ad3c30ae6">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS 14.6.1 (23G93)
- Browser [e.g. chrome, safari] Firefox 
- Version [e.g. 22] 129.0.2

**Comment by rmhari** [comment]
Closed

**Comment by itsraghz** [comment]
Great, the issue looks corrected. Thanks
