### ISSUE TITLE
The layout is not properly aligned

### ISSUE THREAD

**Issue by itsraghz** [sqlcomponents/sqlcomponents#165]
**Describe the bug**
The layout is misaligned on many pages. 

**To Reproduce**

1. Go to 'https://sqlcomponents.org'
2. Click on 'https://sqlcomponents.org/docs/guides/store/'
3. The layout is not properly shown on the source code. 

**Expected behavior**
The source code can be clearly legible. The present structure demands a scroll down even for the obvious contents - the first set. 

**Screenshots**
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/efac40be-765f-4305-ad61-4eea1797b62d">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS 14.6.1 (23G93)
- Browser [e.g. chrome, safari] Firefox 
- Version [e.g. 22] 129.0.2 (64-bit)

**Comment by rmhari** [comment]
Closed
