### ISSUE TITLE
[Mapper|Compiler|Crawler| Support for Stored procedure/Function in postgresql

### ISSUE THREAD

**Issue by rajaduraikrishna** [sqlcomponents/sqlcomponents#166]
Feature: Postgresql supports both stored procedures and functions. We need to add the feature the handle both

# The first example has two steps

Scenario: Database developer created a stored procedure and a function
When the database developer runs the Compiler
Then the database developer waits for a Generated Code to call the stored procedure and function

**Comment by rmhari** [comment]
@rajaduraikrishna Please add docs at https://sqlcomponents.org/docs/guides/stored-procedure/
