### ISSUE TITLE
Compiler - When Point data type used in postgresql compiler is not generating the code properly. Gives compilation error

### ISSUE THREAD

**Issue by rajaduraikrishna** [sqlcomponents/sqlcomponents#168]
**Describe the bug**
When Point data type used in postgresql compiler is not generating the code properly. Gives compilation error

**To Reproduce**
Create following tables in your schema and run JavaCompilerTest.java
create table building (id numeric primary key, name varchar(100), location point, facility_id numeric references facility(id));
create table floor (id numeric primary key, name varchar(50), building_id numeric references building)id));

**Expected behavior**
Generated code should be proper and compile successfully 

**Additional context**
it is tyring to generate PGpoint but the corresponding import statement is not there

**Comment by rmhari** [comment]
Fixed
