### ISSUE TITLE
Compiler - Datatime Columns throw Compiler Error

### ISSUE THREAD

**Issue by rajaduraikrishna** [sqlcomponents/sqlcomponents#169]
Create following table and run the compiler to generate the code.

CREATE TABLE example_table (
    int_column INTEGER,
    bigint_column BIGINT,
    smallint_column SMALLINT,
    tinyint_column SMALLINT,
    float_column REAL,
    decimal_column NUMERIC(10, 2),
    numeric_column NUMERIC(10, 2),
    char_column CHAR(10),
    varchar_column VARCHAR(50),
    text_column TEXT,
    date_column DATE,
    datetime_column TIMESTAMP,
    time_column TIME,
    bit_column BOOLEAN,
    bytea_column BYTEA,
    json_column JSON,
    xml_column XML
);

It generates the code but, for DatetimeColumnColumn it is not having the get method generated and overridden which results in compilation error.

**Comment by rmhari** [comment]
This issue is specific to datatime column

```sql

drop table if exists example_table;

CREATE TABLE example_table (
datetime_column TIMESTAMP
);
```

**Comment by rmhari** [comment]
Iy should bne added to raja table

**Comment by rmhari** [comment]
It us fixed
