### ISSUE TITLE
code is not compiling on jdk 17

### ISSUE THREAD

**Issue by nagkumar** [sqlcomponents/sqlcomponents#17]
`> sqlcomponents\maven-plugin>mvn clean package
`
Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/6.2/asm-6.2.jar (111 kB at 14 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/com/thoughtworks/qdox/qdox/2.0-M9/qdox-2.0-M9.jar (317 kB at 36 kB/s)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to G:\DWork\opensource\jug\sc\sqlcomponents\maven-plugin\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:20 min
[INFO] Finished at: 2022-03-19T19:50:07+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sqlcomponents-maven-plugin: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x2e17a321) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x2e17a321 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sathishk** [comment]
Fixed. Issue was due to old Lombok version which was not compatible with Java 17

**Comment by nagkumar** [comment]
It is always good to auto update complete dependencies in CI/CD to make sure, code is compatible with latest by updating pom.xml automatically with

**Comment by rmhari** [comment]
It is done
