### ISSUE TITLE
[Refactoring] Maven checkstyle goal as per sunmicrosystems rules support

### ISSUE THREAD

**Issue by nagkumar** [sqlcomponents/sqlcomponents#71]
Bring in checkstyle to incorporate the necessary code style checks.. [https://maven.apache.org/plugins/maven-checkstyle-plugin/index.html](https://maven.apache.org/plugins/maven-checkstyle-plugin/index.html)
and suppresstion file used is [sqlcomponents\checkstyle-suppressions.xml](url)
suppression file used is empty

```
<?xml version="1.0"?>
<!DOCTYPE suppressions PUBLIC
	"-//Puppy Crawl//DTD Suppressions 1.1//EN"
	"http://www.puppycrawl.com/dtds/suppressions_1_1.dtd">
<suppressions>
<!--    <suppress files="[\\/]org[\\/]example" checks="."/>-->
</suppressions>
```

The command line to use to check is

`mvn checkstyle:checkstyle`

![image](https://github.com/sqlcomponents/sqlcomponents/assets/332234/1e0cac9a-8b2c-4e4b-b2a1-cf434fe0ac42)

**Comment by nagkumar** [comment]
`mvn checkstyle:check
`
As of today it reports o voilations.. 
![image](https://github.com/sqlcomponents/sqlcomponents/assets/332234/08554ee1-d2fc-4bc0-bfc9-a9a2af96373d)

Great work @rmhari

**Comment by nagkumar** [comment]
However as per google style, it reports issues

![image](https://github.com/sqlcomponents/sqlcomponents/assets/332234/69f40095-04c1-411a-bbdb-fe75c5c4ed7d)

**Comment by sathishk** [comment]
@nagkumar only one check file we shal adhere to as there will be conflicts in standard. now checkstyle is part of ci cd without this build will fail. so closing the issue
